name: weekly scrape

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security scan
        run: |
          yarn npm audit -A
          echo "Security scan completed at $(date)"
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel requests beautifulsoup4 jsonpickle
      - name: Scrape
        run: python scrapers/scrape.py > data.json
      - name: Commit and Push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f data.json
          git commit -m "chore: automated changes by script"
          git push
